version: '3.8'

services:
  # 在线闹钟应用
  online-time-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: online-time:latest
    container_name: online-time-app
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - NGINX_WORKER_PROCESSES=auto
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.online-time.rule=Host(`localhost`)"
      - "traefik.http.services.online-time.loadbalancer.server.port=80"
    networks:
      - online-time-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx负载均衡器（可选，用于多实例部署）
  nginx-lb:
    image: nginx:alpine
    container_name: online-time-nginx-lb
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx-lb.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - online-time-app
    networks:
      - online-time-network
    profiles:
      - lb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 监控服务（可选）
  prometheus:
    image: prom/prometheus:latest
    container_name: online-time-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - online-time-network
    profiles:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  online-time-network:
    driver: bridge
    name: online-time-network

volumes:
  prometheus-data:
    name: online-time-prometheus-data