# 应用级告警规则
groups:
  - name: online-time-app
    rules:
      # 应用服务不可用
      - alert: OnlineTimeAppDown
        expr: up{job="online-time-app"} == 0
        for: 1m
        labels:
          severity: critical
          service: online-time-app
        annotations:
          summary: "Online Time application is down"
          description: "Online Time application has been down for more than 1 minute."
          runbook_url: "https://wiki.example.com/runbooks/online-time-down"

      # HTTP响应时间过高
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(nginx_http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: online-time-app
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for more than 5 minutes."

      # 错误率过高
      - alert: HighErrorRate
        expr: rate(nginx_http_requests_total{status=~"5.."}[5m]) / rate(nginx_http_requests_total[5m]) > 0.05
        for: 3m
        labels:
          severity: warning
          service: online-time-app
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for more than 3 minutes."

      # 容器重启频繁
      - alert: ContainerRestartingTooOften
        expr: increase(docker_container_restart_count[1h]) > 3
        for: 0m
        labels:
          severity: warning
          service: online-time-app
        annotations:
          summary: "Container restarting too often"
          description: "Container {{ $labels.name }} has restarted {{ $value }} times in the last hour."

      # 容器CPU使用率过高
      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total{name="online-time-app"}[5m]) * 100 > 80
        for: 10m
        labels:
          severity: warning
          service: online-time-app
        annotations:
          summary: "High CPU usage detected"
          description: "Container CPU usage is {{ $value }}% for more than 10 minutes."

      # 容器内存使用率过高
      - alert: HighMemoryUsage
        expr: (container_memory_usage_bytes{name="online-time-app"} / container_spec_memory_limit_bytes{name="online-time-app"}) * 100 > 85
        for: 10m
        labels:
          severity: warning
          service: online-time-app
        annotations:
          summary: "High memory usage detected"
          description: "Container memory usage is {{ $value }}% for more than 10 minutes."

      # 磁盘空间不足
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 20
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Disk space is running low"
          description: "Available disk space is {{ $value }}% on {{ $labels.instance }}."

      # 磁盘空间严重不足
      - alert: DiskSpaceCritical
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 10
        for: 1m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Disk space is critically low"
          description: "Available disk space is {{ $value }}% on {{ $labels.instance }}."

      # 网络连接数过高
      - alert: TooManyConnections
        expr: nginx_connections_active > 1000
        for: 5m
        labels:
          severity: warning
          service: nginx
        annotations:
          summary: "Too many active connections"
          description: "Nginx has {{ $value }} active connections for more than 5 minutes."

  - name: monitoring-system
    rules:
      # Prometheus服务不可用
      - alert: PrometheusDown
        expr: up{job="prometheus"} == 0
        for: 1m
        labels:
          severity: critical
          service: prometheus
        annotations:
          summary: "Prometheus monitoring is down"
          description: "Prometheus has been down for more than 1 minute."

      # Grafana服务不可用
      - alert: GrafanaDown
        expr: up{job="grafana"} == 0
        for: 2m
        labels:
          severity: warning
          service: grafana
        annotations:
          summary: "Grafana dashboard is down"
          description: "Grafana has been down for more than 2 minutes."

      # AlertManager服务不可用
      - alert: AlertManagerDown
        expr: up{job="alertmanager"} == 0
        for: 1m
        labels:
          severity: critical
          service: alertmanager
        annotations:
          summary: "AlertManager is down"
          description: "AlertManager has been down for more than 1 minute."