services:
  # 应用服务 - 1Panel单容器模式
  online-time:
    build:
      context: ..
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE:-online-time:latest}
    container_name: online-time-app
    restart: unless-stopped
    ports:
      - "${EXTERNAL_PORT:-9653}:9653"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
    networks:
      - online-time-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9653/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - ./logs:/var/log/nginx
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
    labels:
      - "app.name=online-time"
      - "app.version=${VERSION:-latest}"
      - "deployment.type=1panel-ready"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # # Nginx 反向代理
  # nginx:
  #   image: nginx:alpine
  #   container_name: online-time-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "${HTTP_PORT:-80}:80"
  #   volumes:
  #     - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./logs:/var/log/nginx
  #   depends_on:
  #     - app
  #   networks:
  #     - app-network
  #   healthcheck:
  #     test:
  #       [
  #         "CMD",
  #         "wget",
  #         "--quiet",
  #         "--tries=1",
  #         "--spider",
  #         "http://localhost:80/health",
  #       ]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 3

networks:
  online-time-network:
    driver: bridge
    labels:
      - "app.network=online-time"
      - "deployment.type=1panel"
