global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 在线闹钟应用监控
  - job_name: 'online-time-app'
    static_configs:
      - targets: ['online-time-app:80']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx负载均衡器监控
  - job_name: 'nginx-lb'
    static_configs:
      - targets: ['nginx-lb:80']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s