groups:
  # 响应时间告警
  - name: response_time_alerts
    interval: 30s
    rules:
      - alert: HighResponseTime
        expr: |
          histogram_quantile(0.95,
            sum(rate(nginx_http_request_duration_seconds_bucket[5m])) by (le)
          ) > 0.5
        for: 5m
        labels:
          severity: warning
          component: nginx
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s (threshold: 0.5s)"

      - alert: VeryHighResponseTime
        expr: |
          histogram_quantile(0.99,
            sum(rate(nginx_http_request_duration_seconds_bucket[5m])) by (le)
          ) > 1
        for: 2m
        labels:
          severity: critical
          component: nginx
        annotations:
          summary: "Very high response time detected"
          description: "99th percentile response time is {{ $value }}s (threshold: 1s)"

  # 错误率告警
  - name: error_rate_alerts
    interval: 30s
    rules:
      - alert: HighErrorRate
        expr: |
          sum(rate(nginx_http_requests_total{status=~"5.."}[5m])) /
          sum(rate(nginx_http_requests_total[5m])) > 0.01
        for: 5m
        labels:
          severity: warning
          component: nginx
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} (threshold: 1%)"

      - alert: VeryHighErrorRate
        expr: |
          sum(rate(nginx_http_requests_total{status=~"5.."}[5m])) /
          sum(rate(nginx_http_requests_total[5m])) > 0.05
        for: 2m
        labels:
          severity: critical
          component: nginx
        annotations:
          summary: "Very high error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} (threshold: 5%)"

  # 资源使用告警
  - name: resource_alerts
    interval: 30s
    rules:
      - alert: HighCPUUsage
        expr: |
          rate(container_cpu_usage_seconds_total{name="online-time"}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
          component: container
        annotations:
          summary: "High CPU usage detected"
          description: "Container CPU usage is {{ $value }}% (threshold: 80%)"

      - alert: HighMemoryUsage
        expr: |
          container_memory_usage_bytes{name="online-time"} /
          container_spec_memory_limit_bytes{name="online-time"} * 100 > 80
        for: 5m
        labels:
          severity: warning
          component: container
        annotations:
          summary: "High memory usage detected"
          description: "Container memory usage is {{ $value }}% (threshold: 80%)"

      - alert: DiskSpaceRunningOut
        expr: |
          node_filesystem_avail_bytes{mountpoint="/"} /
          node_filesystem_size_bytes{mountpoint="/"} * 100 < 10
        for: 5m
        labels:
          severity: critical
          component: system
        annotations:
          summary: "Disk space running out"
          description: "Only {{ $value }}% disk space remaining"

  # 流量告警
  - name: traffic_alerts
    interval: 30s
    rules:
      - alert: HighTrafficVolume
        expr: |
          sum(rate(nginx_http_requests_total[5m])) > 1000
        for: 5m
        labels:
          severity: info
          component: nginx
        annotations:
          summary: "High traffic volume detected"
          description: "Request rate is {{ $value }} req/s (threshold: 1000 req/s)"

      - alert: TrafficSpike
        expr: |
          sum(rate(nginx_http_requests_total[1m])) /
          sum(rate(nginx_http_requests_total[5m] offset 5m)) > 3
        for: 2m
        labels:
          severity: warning
          component: nginx
        annotations:
          summary: "Traffic spike detected"
          description: "Traffic increased by {{ $value }}x compared to 5 minutes ago"

  # 缓存性能告警
  - name: cache_alerts
    interval: 30s
    rules:
      - alert: LowCacheHitRate
        expr: |
          nginx_cache_hits / (nginx_cache_hits + nginx_cache_misses) < 0.8
        for: 10m
        labels:
          severity: warning
          component: cache
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }} (threshold: 80%)"

      - alert: RedisHighMemoryUsage
        expr: |
          redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
          component: redis
        annotations:
          summary: "Redis high memory usage"
          description: "Redis memory usage is {{ $value }}% (threshold: 90%)"

  # 可用性告警
  - name: availability_alerts
    interval: 30s
    rules:
      - alert: ServiceDown
        expr: up{job="app-metrics"} == 0
        for: 1m
        labels:
          severity: critical
          component: app
        annotations:
          summary: "Service is down"
          description: "{{ $labels.instance }} has been down for more than 1 minute"

      - alert: HealthCheckFailing
        expr: |
          probe_success{job="blackbox"} == 0
        for: 2m
        labels:
          severity: critical
          component: health
        annotations:
          summary: "Health check failing"
          description: "Health check for {{ $labels.instance }} has been failing for 2 minutes"

  # 性能基准告警
  - name: performance_benchmark_alerts
    interval: 30s
    rules:
      - alert: FirstContentfulPaintSlow
        expr: |
          web_vitals_fcp_seconds{quantile="0.75"} > 1.8
        for: 10m
        labels:
          severity: warning
          component: frontend
        annotations:
          summary: "First Contentful Paint is slow"
          description: "75th percentile FCP is {{ $value }}s (threshold: 1.8s)"

      - alert: LargestContentfulPaintSlow
        expr: |
          web_vitals_lcp_seconds{quantile="0.75"} > 2.5
        for: 10m
        labels:
          severity: warning
          component: frontend
        annotations:
          summary: "Largest Contentful Paint is slow"
          description: "75th percentile LCP is {{ $value }}s (threshold: 2.5s)"

      - alert: HighCumulativeLayoutShift
        expr: |
          web_vitals_cls{quantile="0.75"} > 0.1
        for: 10m
        labels:
          severity: warning
          component: frontend
        annotations:
          summary: "High Cumulative Layout Shift"
          description: "75th percentile CLS is {{ $value }} (threshold: 0.1)"

      - alert: HighFirstInputDelay
        expr: |
          web_vitals_fid_milliseconds{quantile="0.75"} > 100
        for: 10m
        labels:
          severity: warning
          component: frontend
        annotations:
          summary: "High First Input Delay"
          description: "75th percentile FID is {{ $value }}ms (threshold: 100ms)"